%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% This file was autogenerated by PaperShell v3 
%% https://github.com/sylvainhalle/PaperShell
%% DO NOT EDIT!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[conference]{IEEEtran}

% Usual packages
\usepackage[utf8]{inputenc}            % UTF-8 input encoding
\usepackage[T1]{fontenc}               % Type1 fonts
\usepackage[english]{babel}            % Hyphenation
\usepackage{graphicx}                  % Import graphics
\usepackage{cite}                      % Better handling of citations
\usepackage{comment}                   % To comment out blocks of text
\usepackage{flushend}                  % To balance columns on last page
\usepackage{microtype}                 % Better typesetting
\usepackage[scaled]{helvet}            % Scale Helvetica
\usepackage[bookmarks=false]{hyperref} % Better handling of references in PDFs

% Title
\title\{%
\{\{ title }}%
\}

% Authors and affiliations
\author{%
\IEEEauthorblockN\{%
{% local a = 0 %}
}}


\input{includes.tex}
\usepackage{newtxtext,newtxmath} % Times with math support. Must be placed here to avoid clash if amsthm is loaded in includes

% Default path for graphicspath
\graphicspath{fig/}

\begin{document}

\maketitle

\begin{abstract}
\input{abstract.tex}
\end{abstract}

% Fixing bug in the definition of \\markboth in IEEEtran class
% See http://tex.stackexchange.com/a/88864
\makeatletter
\let\l@ENGLISH\l@english
\makeatother