%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% This file was autogenerated by PaperShell v3 
%% https://github.com/sylvainhalle/PaperShell
%% DO NOT EDIT!
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[sigconf]{acmart}

% Usual packages
\usepackage[utf8]{inputenc}  % UTF-8 input encoding
\usepackage[T1]{fontenc}     % Type1 fonts
\usepackage[english]{babel}  % Hyphenation
\usepackage{graphicx}        % Import graphics
\usepackage{comment}         % To comment out blocks of text
\usepackage{flushend}        % To balance columns on last page

\begin{document}


\title{%
{{ title or "" }}%
}

\begin{abstract}
\input{abstract.tex}
\end{abstract}

%\input{acm-ccs.tex}
\keywords{%
{{ keywords or "" }}%
}
\maketitle